RISCV_ARCH := rv32im
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


TARGET = main


CFLAGS += -DSIMULATION
#CFLAGS += -O2
# ASM_SRCS +=$(COMMON_DIR)/csr_read_write.S
#LDFLAGS +=
#INCLUDES += -I.

C_SRCS := \
	main.c \
	



COMMON_DIR = ./
TOOLCHAIN_DIR = C:\Users\limy\Desktop\tinyriscv-master
include ./common.mk
